### PR TITLE
#166171820 Fix transaction amounts

### PR DESCRIPTION
**Pull request by ayodejiAA**
#### What does this PR do?
Introduce a fix to convert transaction amounts from string to number. 

#### Description of Task to be completed?
Convert amount value to number.

#### How should this be manually tested?
- Clone the repo and start server- ```npm run startDev```

- Using Postman or Insomnia, make a POST request to any of these endpoints ```/api/v1/transactions/<accontNumber>/debit``` or ```/api/v1/transactions/<accontNumber>/credit```. Add an existing account number or create one. 

- Add a staff (cashier) token, make a debit/credit transaction request with any amount and then send .

#### Any background context you want to provide?
The application allows a cashier to make credit and debit transaction on any active client account. So when a cashier makes any of these transactions, the amount value should add to or deduct from old balance, as opposed to concatenating with old balance.

#### What are the relevant pivotal tracker stories?
[[#166171820]](https://www.pivotaltracker.com/n/projects/2350042/stories/166171820)

#### Screenshots (if appropriate)
amountError

### CODE REVIEW

**Comment by chiboycalix** [comment]
Nice Job here. I like the fact that you got rid of commented codes.

**Review by abdulfatai360 — APPROVED** [review]
Nice work @Xwebyna . For the purpose of another time, you should consider making PR to have just a single commit.

**Review by chiboycalix — APPROVED** [review]
Nice Job.

**Review by tolulope-od — APPROVED** [review]

**Comment by ayodejiAA** [comment]
> Nice work @Xwebyna . For the purpose of another time, you should consider making PR to have just a single commit.

Noted. Thanks!

**Pull request merged**
