### PR TITLE
#166164550 User should be able to view accounts they own via the API endpoint

### PR DESCRIPTION
**Pull request by tolulope-od**
#### What does this PR do?
Fixes an issue where a user could not fetch all the accounts they own
Fixes an issue where a request to the GET accounts routes throws a server error
Adds an error handling middleware with a specified server response
Adds test for successful fetching of accounts

#### Description of Task to be completed?
Have the following endpoint working for a user to fetch all accounts they own:
`GET -> /api/v1/accounts`

#### How should this be manually tested?
After cloning the repo, `cd` into it and do the following:
```bash
# install dependencies
$ npm install

# run unit tests
$ npm test

# start the development server
$ npm run startDev
```
Using Postman, sign in as a `client` and visit the route stated above

#### Any background context you want to provide?
As an authenticated user, a request to the `GET` all accounts API endpoint to return all accounts owned by a user in an Array, if there are no accounts for that user, an empty array should be returned, this PR fixes those issues.

#### What are the relevant pivotal tracker stories?
[#166164550](https://www.pivotaltracker.com/story/show/166164550)

#### Screenshots (if appropriate)
Screenshot 2019-05-22 at 12 37 04 PM

### CODE REVIEW

**Review by chialuka — APPROVED** [review]
The destructuring on the accountController.js file is suberp. The way you also handled the accountTest.js file and its ESLint rules is admirable. Great job!

**Review by obayomi96 — COMMENTED** [review]
The way you refactored the Eslint rules, the test cases and especially the implementation of the getAllAccounts is brilliant. This is a job well done, i'm very impressed.

**Review by abdulfatai360 — APPROVED** [review]
Seems you have been coding for a very long time... Well done @tolulope-od

**Comment by tolulope-od** [comment]
> Seems you have been coding for a very long time... Well done @tolulope-od

It'll be a year on the 9th of July! Thanks! 😁

**Review by Nerocodes — APPROVED** [review]
Great job! I see you also added a test to get all accounts, good one.

**Pull request merged**
