### PR TITLE
#166260583 Users can request for reset password link and reset password

### PR DESCRIPTION
**Pull request by ayodejiAA**
#### What does this PR do?
Create user password reset endpoints to request for reset link and change password

#### Description of Task to be completed?
have the following endpoints working:
- POST ```/api/v1/resetlink```
- PATCH ```api/v1/resetpassword/:id/:oneTimeToken```

$ npm install
Run unit tests 
$ npm test

- Run ```npm run startDev``` . With the use of postman or any other endpoint testing app, sign up an account with a valid email address
- Use reset link endpoint to request for link which will be sent to your valid email address. Required field is ```email```.
- Add hostname to link sent, post to postman and enter new password in the request body. Required field is ```password```.

#### Any background context you want to provide?
The reset link sent to user includes a one-time use token and expires after 30 minutes.

#### What are the relevant pivotal tracker stories?
- [#166260583](https://www.pivotaltracker.com/story/show/166260583)

#### Screenshots (if appropriate)

***

***

### CODE REVIEW

**Review by Nerocodes — COMMENTED** [review]
Awesome stuff. There were quite a lot of changes, I think the whole team will have to review this before it's merged

**Review by chialuka — APPROVED** [review]
@Xwebyna, this is nothing short of excellent. You have singlehandedly combed through and revamped the code base. You not only did excellent housekeeping, but you also added a very cool feature. Thumbs up.

**Comment by ayodejiAA** [comment]
> @Xwebyna, this is nothing short of excellent. You have singlehandedly combed through and revamped the code base. You not only did excellent housekeeping, but you also added a very cool feature. Thumbs up.

Thanks alot. @LukasChiama

**Review by tolulope-od — APPROVED** [review]
Wow! This is massive! Awesome job @Xwebyna So much programming jujitsu going on here, lol. I learned a lot just reading the diffs. This is great stuff!

**Comment by ayodejiAA** [comment]
> Wow! This is massive! Awesome job @Xwebyna So much programming jujitsu going on here, lol. I learned a lot just reading the diffs. This is great stuff!

 Thank you, @tolulope-od. I appreciate your kind words.

**Review by Nerocodes — APPROVED** [review]

**Pull request merged**
