### PR TITLE
#166209289 User can receive transaction notifications via email

### PR DESCRIPTION
**Pull request by tolulope-od**
#### What does this PR do?
Adds email notification for transactions
Adds tests for successful transactions
Refactors account test on PR #5 
Updates authentication logic from PR #7 

#### Description of Task to be completed?
A user should be able to receive email notifications whenever a transaction is authorised on my account via these routes: 
`POST ->  api/v1/transactions/:accountNumber/debit`
`POST ->  api/v1/transactions/:accountNumber/credit`

#### How should this be manually tested?
After cloning the repo, `cd` into it and do the following:
```bash
# install dependencies
$ npm install

# run unit tests
$ npm test

# start the development server
$ npm run startDev
```
Using Postman, sign in as a `staff` and visit the routes stated above with an account number owned by a user with a valid email address

#### Any background context you want to provide?
The sending of email notifications is configured to be handled by a [gmail](mail.google.com) service and if you would like to test that feature you can do so by using a Google email account. Although you might need to allow [less secure apps](https://blogs.msmvps.com/jcoehoorn/blog/2017/05/04/what-are-less-secure-apps-in-google/) which can be done [here](https://myaccount.google.com/lesssecureapps)

The tests on the codebase were structured to work without a database, so the features implemented were not initially tested against a database to ensure they worked as they should, this PR also addresses that issue by writing test cases for the feature implemented against a test database

#### What are the relevant pivotal tracker stories?
[#166209289 ](https://www.pivotaltracker.com/story/show/166209289)

#### Screenshots (if appropriate)
**Email Notification**
Screenshot 2019-05-23 at 1 52 30 PM

**Test Coverage Against Local Database**
Screenshot 2019-05-23 at 7 20 26 PM

### CODE REVIEW

**Review by chialuka — APPROVED** [review]
Awesome job! This is well done. In the package.json file though, the `npm run dbtest` script runs the migration and seed script. With the current arrangement, running that script will likely produce an error because the seed script will be run twice.
This I think can be fixed in another branch.
Your work is so, so good. Keep it up for real

**Comment by tolulope-od** [comment]
> Awesome job! This is well done. In the package.json file though, the `npm run dbtest` script runs the migration and seed script. With the current arrangement, running that script will likely produce an error because the seed script will be run twice.
> This I think can be fixed in another branch.
> Your work is so, so good. Keep it up for real

@LukasChiama thank you for pointing that out, I must have missed it when I adjusted the script. Thanks again for the feedback!

**Review by obayomi96 — APPROVED** [review]
Great job  @tolulope-od .  The refactoring you did is very impressive. You refactored the tests cases and implemented the email notifications. Well done this is fine code.

**Comment by chialuka** [comment]
Our test coverage also shot up by about 10% thanks to this commit. Thumbs up Tolu

**Review by ayodejiAA — APPROVED** [review]
Job well done. I like what you did with the transaction controller, and the fact that you were able to increase the test coverage. Cool!

**Review by abdulfatai360 — COMMENTED** [review]
Make e no be like say I no talk... Again, well done for the good job. I love the initiative by allowing other team members to review and merge this PR (_rules are not cast on stone_).

**Pull request merged**
