### PR TITLE
#166231219 Implement signin and signup page consuming api endpoint

### PR DESCRIPTION
**Pull request by Nerocodes**
> start the development server
>$ npm run startDev
>run the UI folder on a server
>navigate to sign in or sign up page

#### Any background context you want to provide?
none

#### What are the relevant pivotal tracker stories?
[#166231219](https://www.pivotaltracker.com/story/show/166231219)

##### Sign up
Banka   Register

##### Sign in
Banka   Sign in

##### Client dashboard
Banka   Client dashboard

### CODE REVIEW

**Review by chialuka — APPROVED** [review]
Good job Nero. Pulling this off in such a short time is admirable

**Comment by ayodejiAA** [comment]
Totally a wonderful job @Nerocodes

**Review by obayomi96 — COMMENTED** [review]
Good job @Nerocodes .

**Comment by tolulope-od** [comment]
Awesome stuff @Nerocodes given the time constraint, you still pulled this off. Thank you! This is wonderful!

**Pull request merged**
